// Databricks SQL / Spark SQL keywords — comprehensive list
export const KEYWORDS = new Set([
  // DML
  'SELECT', 'FROM', 'WHERE', 'GROUP', 'BY', 'ORDER', 'HAVING', 'LIMIT',
  'OFFSET', 'UNION', 'ALL', 'INTERSECT', 'EXCEPT', 'INSERT', 'INTO',
  'VALUES', 'UPDATE', 'SET', 'DELETE', 'MERGE', 'WHEN', 'MATCHED', 'THEN',
  'NOT', 'AND', 'OR', 'IN', 'EXISTS', 'BETWEEN', 'LIKE', 'RLIKE', 'ILIKE', 'IS',
  'NULL', 'TRUE', 'FALSE', 'AS', 'ON', 'USING', 'CASE', 'WHEN', 'THEN',
  'ELSE', 'END', 'CAST', 'TRY_CAST', 'DISTINCT', 'ASC', 'DESC', 'NULLS',
  'FIRST', 'LAST', 'SOME', 'ANY', 'ESCAPE',

  // Joins
  'JOIN', 'INNER', 'LEFT', 'RIGHT', 'FULL', 'OUTER', 'CROSS', 'SEMI',
  'ANTI', 'NATURAL', 'LATERAL',

  // DDL
  'CREATE', 'ALTER', 'DROP', 'TABLE', 'VIEW', 'DATABASE', 'SCHEMA',
  'IF', 'REPLACE', 'TEMPORARY', 'TEMP', 'EXTERNAL', 'LOCATION',
  'FUNCTION', 'RETURNS', 'RETURN',
  'COMMENT', 'TBLPROPERTIES', 'PARTITIONED', 'CLUSTERED', 'SORTED',
  'BUCKETS', 'STORED', 'ROW', 'FORMAT', 'DELIMITED', 'FIELDS',
  'TERMINATED', 'COLLECTION', 'ITEMS', 'MAP', 'KEYS', 'LINES',
  'SERDE', 'SERDEPROPERTIES', 'WITH', 'CONSTRAINT', 'PRIMARY',
  'FOREIGN', 'REFERENCES', 'CHECK', 'DEFAULT', 'INDEX', 'GENERATED',
  'ALWAYS', 'IDENTITY', 'CASCADE', 'RESTRICT', 'UNIQUE',
  'REFRESH', 'CACHE', 'UNCACHE', 'ANALYZE', 'COMPUTE', 'STATISTICS',
  'MSCK', 'REPAIR', 'TRUNCATE', 'RENAME', 'ADD',

  // Databricks-specific
  'OPTIMIZE', 'ZORDER', 'VACUUM', 'DESCRIBE', 'DETAIL', 'HISTORY',
  'CONVERT', 'TO', 'DELTA', 'RESTORE', 'VERSION', 'TIMESTAMP',
  'CLONE', 'SHALLOW', 'DEEP', 'COPY', 'OVERWRITE', 'DIRECTORY',
  'DBPROPERTIES', 'CATALOG', 'USE', 'SHOW', 'TABLES', 'VIEWS',
  'DATABASES', 'SCHEMAS', 'COLUMNS', 'FUNCTIONS', 'GRANT', 'REVOKE',
  'DENY', 'PRIVILEGES', 'IDENTIFIER', 'UNPIVOT', 'PIVOT',
  'LANGUAGE', 'METRICS',

  // Data types
  'INT', 'INTEGER', 'BIGINT', 'SMALLINT', 'TINYINT', 'FLOAT', 'DOUBLE',
  'DECIMAL', 'NUMERIC', 'STRING', 'VARCHAR', 'CHAR', 'BOOLEAN', 'DATE',
  'TIMESTAMP', 'BINARY', 'ARRAY', 'STRUCT', 'MAP', 'INTERVAL', 'VOID',

  // Window clause keywords
  'OVER', 'PARTITION', 'ROWS', 'RANGE', 'UNBOUNDED', 'PRECEDING',
  'FOLLOWING', 'CURRENT', 'ROW',

  // Window functions
  'ROW_NUMBER', 'RANK', 'DENSE_RANK', 'NTILE', 'LEAD', 'LAG',
  'FIRST_VALUE', 'LAST_VALUE', 'NTH_VALUE', 'CUME_DIST', 'PERCENT_RANK',

  // Aggregate functions
  'COUNT', 'SUM', 'AVG', 'MIN', 'MAX', 'COUNT_IF', 'ARRAY_AGG',
  'COLLECT_LIST', 'COLLECT_SET', 'APPROX_COUNT_DISTINCT',
  'PERCENTILE', 'PERCENTILE_APPROX', 'PERCENTILE_CONT', 'PERCENTILE_DISC',
  'STDDEV', 'STDDEV_POP', 'STDDEV_SAMP',
  'VARIANCE', 'VAR_POP', 'VAR_SAMP',
  'CORR', 'COVAR_POP', 'COVAR_SAMP',
  'SKEWNESS', 'KURTOSIS', 'MEDIAN', 'MODE',
  'BOOL_AND', 'BOOL_OR', 'EVERY',
  'BIT_AND', 'BIT_OR', 'BIT_XOR',
  'TRY_AVG', 'TRY_SUM',
  'REGR_AVGX', 'REGR_AVGY', 'REGR_COUNT', 'REGR_R2',
  'REGR_SLOPE', 'REGR_INTERCEPT', 'REGR_SXX', 'REGR_SXY', 'REGR_SYY',

  // Conditional functions
  'COALESCE', 'NULLIF', 'NVL', 'NVL2', 'IFNULL', 'IFF', 'NANVL',

  // String functions
  'CONCAT', 'CONCAT_WS', 'SUBSTRING', 'SUBSTR', 'TRIM', 'LTRIM', 'RTRIM',
  'UPPER', 'LOWER', 'LENGTH', 'LPAD', 'RPAD', 'REPLACE', 'TRANSLATE',
  'SPLIT', 'REGEXP_REPLACE', 'REGEXP_EXTRACT', 'REGEXP_EXTRACT_ALL',
  'REGEXP_LIKE', 'REGEXP', 'INSTR', 'LOCATE', 'INITCAP', 'REVERSE',
  'REPEAT', 'SPACE', 'FORMAT_STRING', 'FORMAT_NUMBER',
  'BASE64', 'UNBASE64', 'ENCODE', 'DECODE', 'ASCII', 'CHR',
  'CHAR_LENGTH', 'CHARACTER_LENGTH', 'OCTET_LENGTH', 'BIT_LENGTH',
  'SOUNDEX', 'LEVENSHTEIN', 'OVERLAY', 'POSITION',
  'CONTAINS', 'STARTSWITH', 'ENDSWITH', 'LCASE', 'UCASE', 'BTRIM',
  'LEFT', 'RIGHT', 'TRY_TO_NUMBER',

  // Date/time functions
  'CURRENT_DATE', 'CURRENT_TIMESTAMP', 'NOW',
  'DATE_ADD', 'DATE_SUB', 'DATEDIFF', 'DATE_FORMAT', 'DATE_TRUNC',
  'DATE_PART', 'DATEADD', 'DATEPART', 'TIMEDIFF',
  'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND', 'QUARTER',
  'DAYOFWEEK', 'DAYOFYEAR', 'WEEKOFYEAR',
  'TO_DATE', 'TO_TIMESTAMP', 'FROM_UNIXTIME', 'UNIX_TIMESTAMP',
  'TRUNC', 'ADD_MONTHS', 'MONTHS_BETWEEN', 'LAST_DAY', 'NEXT_DAY',
  'MAKE_DATE', 'MAKE_TIMESTAMP', 'MAKE_INTERVAL',
  'EXTRACT', 'TIMESTAMPADD', 'TIMESTAMPDIFF', 'TRY_TO_TIMESTAMP',

  // Math functions
  'ABS', 'CEIL', 'CEILING', 'FLOOR', 'ROUND', 'MOD', 'POWER', 'POW',
  'SQRT', 'CBRT', 'EXP', 'LOG', 'LOG2', 'LOG10', 'LN',
  'RAND', 'RANDOM', 'SIGN', 'SIGNUM',
  'GREATEST', 'LEAST', 'CONV', 'HEX', 'UNHEX', 'BIN',
  'PI', 'DEGREES', 'RADIANS', 'FACTORIAL', 'PMOD', 'WIDTH_BUCKET',
  'POSITIVE', 'NEGATIVE',
  'SIN', 'COS', 'TAN', 'ASIN', 'ACOS', 'ATAN', 'ATAN2',
  'SINH', 'COSH', 'TANH',
  'TRY_ADD', 'TRY_DIVIDE', 'TRY_MULTIPLY', 'TRY_SUBTRACT',
  'SHIFTLEFT', 'SHIFTRIGHT', 'SHIFTRIGHTUNSIGNED',

  // Collection functions
  'ARRAY_CONTAINS', 'ARRAY_DISTINCT', 'ARRAY_EXCEPT', 'ARRAY_INTERSECT',
  'ARRAY_JOIN', 'ARRAY_MAX', 'ARRAY_MIN', 'ARRAY_POSITION',
  'ARRAY_REMOVE', 'ARRAY_REPEAT', 'ARRAY_SORT', 'ARRAY_UNION',
  'ARRAY_ZIP', 'ARRAYS_OVERLAP', 'ARRAYS_ZIP',
  'ELEMENT_AT', 'SIZE', 'SLICE', 'SORT_ARRAY', 'FLATTEN', 'SEQUENCE',
  'MAP_KEYS', 'MAP_VALUES', 'MAP_FROM_ARRAYS', 'MAP_FROM_ENTRIES',
  'MAP_CONCAT', 'MAP_FILTER', 'MAP_ZIP_WITH',
  'TRANSFORM', 'FILTER', 'AGGREGATE', 'FORALL', 'REDUCE',
  'EXPLODE', 'EXPLODE_OUTER', 'POSEXPLODE', 'POSEXPLODE_OUTER',
  'INLINE', 'INLINE_OUTER', 'NAMED_STRUCT', 'STACK',

  // JSON functions
  'FROM_JSON', 'TO_JSON', 'JSON_TUPLE', 'GET_JSON_OBJECT',
  'SCHEMA_OF_JSON', 'JSON_ARRAY_LENGTH', 'PARSE_JSON',

  // Hash and misc functions
  'MD5', 'SHA', 'SHA1', 'SHA2', 'CRC32', 'HASH', 'XXHASH64', 'UUID',
  'TYPEOF', 'ASSERT_TRUE', 'RAISE_ERROR',
  'CURRENT_USER', 'CURRENT_DATABASE', 'CURRENT_CATALOG', 'CURRENT_SCHEMA',
  'INPUT_FILE_NAME', 'MONOTONICALLY_INCREASING_ID', 'SPARK_PARTITION_ID',

  // CTE
  'WITH', 'RECURSIVE',

  // Misc
  'TABLESAMPLE', 'PERCENT', 'BUCKET', 'OUT', 'OF', 'DISTRIBUTE',
  'SORT', 'CLUSTER', 'GROUPING', 'SETS', 'CUBE', 'ROLLUP', 'QUALIFY',
  'WINDOW', 'FETCH', 'NEXT', 'ONLY', 'LIMIT', 'OFFSET',
  'LATERAL', 'CROSS', 'APPLY',
]);

// Keywords that start a new major clause (trigger newline + dedent)
export const CLAUSE_KEYWORDS = new Set([
  'SELECT', 'FROM', 'WHERE', 'GROUP BY', 'ORDER BY', 'HAVING', 'LIMIT',
  'UNION', 'UNION ALL', 'INTERSECT', 'EXCEPT', 'INSERT INTO', 'VALUES',
  'UPDATE', 'SET', 'DELETE', 'MERGE INTO', 'WHEN', 'WINDOW',
  'LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN', 'FULL OUTER JOIN',
  'CROSS JOIN', 'LEFT OUTER JOIN', 'RIGHT OUTER JOIN', 'LEFT SEMI JOIN',
  'LEFT ANTI JOIN', 'JOIN', 'ON', 'USING', 'LATERAL VIEW',
  'DISTRIBUTE BY', 'SORT BY', 'CLUSTER BY', 'QUALIFY',
  'OPTIMIZE', 'ZORDER BY', 'PIVOT', 'UNPIVOT',
  'PARTITION BY', 'WITH', 'TBLPROPERTIES',
  'RETURNS', 'RETURN',
  'LANGUAGE',
]);
